---
title: "Time-varying treatment effect dgp"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('~/Dropbox (ASU)/longBet/R/')
```

## DGP

Data Size

```{r}
n = 100
t1 = 40
t0 = 21
p = 1
```

Individual effect

```{r}
# alpha_i ~ N(mu_a, sig_a)
mu_a = 0
sig_a = 1
alpha = rnorm(n, mu_a, sig_a)
```

Time fixed effect

```{r}
# gamma_t ~ N(mu_g, sig_g)
mu_g = 1
sig_g = 1
gamma = rnorm(t1, mu_g, sig_g)
```

Time-varying (lagged) Treatment effect

```{r}
x = as.matrix(rnorm(n))

mu <- function(x, t) {1 + 0.5*x - 0.5*t  + 0.1*x*t}
mu_mat <- outer(as.vector(x), 1:t1, mu)

tau <- function(x){a = (x + 1.5)^2; 5*sqrt(a) + sin(5*a) + 1}
tau_mat <- matrix(0, n, t1-t0+1)
tau_mat[,1] <- tau(x)
for (i in 2:(t1-t0+1)){
  tau_mat[,i] <- 0.9*tau_mat[,i-1]
}
```

Treatment

```{r}
s <- sd(x)
pi <- 0.8*pnorm(3*x / s -0.5*x ) + 0.05 + runif(n)/10
z = rbinom(n, 1, pi)
```

Error term

```{r}
eps = matrix(rnorm(n*t1, 0, 0.2), nrow = n, ncol = t1)
```

Generate observations

```{r}
y0 = y1 = y = matrix(0, nrow = n, ncol = t1)
y0 <- mu_mat
for (i in 1:n){
  y0[i,] = y0[i,] + alpha[i]
}
for (j in 1:t1){
  y0[,j] = y0[,j] + gamma[j]
}
y0 = y0 + eps
y1 = y0
y1[, t0:t1] = y0[, t0:t1] + tau_mat
z_mat = matrix(rep(z, t1), n, t1)
y = y0 * (1-z_mat) + y1 * z_mat
```

Visualize time series

```{r}
plot(1:t1, rep(mu_a, t1), type = "l", col = 3, ylim = range(y), lwd = 2) # mean indiviudal effect
for (i in 1:50){
  lines(1:t1, y[i,], col = 1 + 3*z[i], lty = 2)
}
lines(1:t1, rep(mu_a, t1), col = 3, lwd = 2)
lines(1:t1, gamma, col = 2, lwd = 2) # time effect
legend("topleft", legend = c("Mean Individual Effect", "Time effect", "y untreated", "y treated"), col = c(3, 2, 1, 4), lty = c(1, 1, 2, 2))
```

Visualize treatment effect

```{r}
# treatment effect over x
plot(x, tau_mat[,1])
```

```{r}
# # treatment effect over time
# plot(t0:t1, tau_mat[1,], type = "l", lty = 2, ylim = range(tau_mat))
# for (i in seq(1, n, length.out = 30)){
#   lines(t0:t1, tau_mat[i,], lty=2)
# }
```

## Demo model

Model

```{r}
source('longBet_prog.R')
library(XBCF)
fit <- longBet_prog(y, x, z, t0, 100, 20, 40)
```

```{r}
par(mfrow=c(1,2))
plot(1:t1, colMeans(fit$tauhat[,1,]) , type = "l", col = 1, ylim = range(colMeans(fit$tauhat)),lty = 2, ylab = 'Estimated tauhat over time')
for (i in seq(1, n, length.out = 20)){
  lines(1:t1, colMeans(fit$tauhat[1:10,i,]), col = 1, lty = 2)
}
lines(1:t1, rep(0, t1), col = 3, lty = 1, lwd = 2)
legend("topleft", legend = c("tauhat"), col = c(1), lty = c(1,2))

plot(1:t1, colMeans(fit$tauhat[,1,]) - c(rep(0, t0-1), tau_mat[1,]), type = "l", col = 1, ylim = range(colMeans(fit$tauhat) - c(rep(0, t0-1), tau_mat[1,])),lty = 2, ylab = 'Individual tauhat - tau over time')
for (i in seq(1, n, length.out = 20)){
  lines(1:t1, colMeans(fit$tauhat[,i,]) - c(rep(0, t0-1), tau_mat[i,]), col = 1, lty = 2)
}
lines(1:t1, rep(0, t1), col = 3, lty = 1, lwd = 2)
legend("topleft", legend = c("tauhat - tau"), col = c(1), lty = c(1,2))
```

```{r}
pct_bias <- abs((colMeans(fit$tauhat[,,t0:t1]) - tau_mat) / tau_mat)
par(mfrow=c(1,2))
plot(t0:t1, colMeans(pct_bias), type = "l", col = 1, ylim = range(0, colMeans(pct_bias)),lty = 2, ylab = 'Percentage bias on tau over time', yaxt="n")
lines(t0:t1, rep(0, t1-t0+1), col = 3, lty = 1, lwd = 2)
axis(2, at=pretty(colMeans(pct_bias)), lab=pretty(colMeans(pct_bias)) * 100, las=TRUE)
legend("topleft", legend = c("abs((tauhat - tau )/tau)"), col = c(1), lty = c(1,2))

plot(x, rowMeans(pct_bias), col = 1, ylim = range(0, rowMeans(pct_bias)), ylab = 'Percentage bias on tau over individual', yaxt="n")
axis(2, at=pretty(rowMeans(pct_bias)), lab=pretty(rowMeans(pct_bias)) * 100, las=TRUE)
legend("topleft", legend = c("abs((tauhat - tau )/tau)"), col = c(1), lty = c(1,2))
```

Plot yhat

```{r}
yhat <- colMeans(fit$muhat)
yhat[,t0:t1] <- yhat[,t0:t1] + colMeans(fit$tauhat[,,t0:t1]) * matrix(rep(z, t1-t0+1), n, t1-t0+1)


plot(1:t1, rep(mu_a, t1), type = "l", col = 3, ylim = range(yhat), lwd = 2) # mean indiviudal effect
for (i in 1:50){
  lines(1:t1, yhat[i,], col = 1 + 3*z[i], lty = 2)
}
lines(1:t1, rep(mu_a, t1), col = 3, lwd = 2)
lines(1:t1, gamma, col = 2, lwd = 2) # time effect
legend("topleft", legend = c("Mean Individual Effect", "Time effect", "yhat untreated", "yhat treated"), 
       col = c(3, 2, 1, 4), lty = c(1, 1, 2))
```


treatment bias on time t
```{r}
t <- t0
tau_hat <- colMeans(fit$tauhat[,,t0:t1])
par(mfrow=c(1,2))
plot(x, tau_hat[,t - t0 + 1], col = 1)
points(x, tau_mat[,t-t0+1], col = 2)
plot(x, tau_hat[,t - t0 + 1] - tau_mat[, t-t0+1])
```