---
title: "Time-varying treatment effect dgp"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('~/Dropbox (ASU)/longBet/')
```

## DGP
Data Size
```{r}
n = 100
t1 = 40
t0 = 21
p = 1
```

Individual effect
```{r}
# alpha_i ~ N(mu_a, sig_a)
mu_a = 0
sig_a = 1
alpha = rnorm(n, mu_a, sig_a)
```

Time fixed effect
```{r}
# gamma_t ~ N(mu_g, sig_g)
mu_g = 1
sig_g = 1
gamma = rnorm(t1, mu_g, sig_g)
```

Error term
```{r}
eps = matrix(rnorm(n*t1, 0, 0.2), nrow = n, ncol = t1)
```

Generate observations
```{r}
y0 = y1 = y = matrix(0, nrow = n, ncol = t1)
for (i in 1:n){
  y0[i,] = y0[i,] + alpha[i]
}
for (j in 1:t1){
  y0[,j] = y0[,j] + gamma[j]
}
y0 = y0 + eps
y = y0 
```

Visualize time series
```{r}
plot(1:t1, rep(mu_a, t1), type = "l", col = 3, ylim = range(y), lwd = 2) # mean indiviudal effect
for (i in 1:50){
  lines(1:t1, y[i,], col = 1, lty = 2)
}
lines(1:t1, rep(mu_a, t1), col = 3, lwd = 2)
lines(1:t1, gamma, col = 2, lwd = 2) # time effect
legend("topleft", legend = c("Mean Individual Effect", "Time effect", "y"), col = c(3, 2, 1), lty = c(1, 1, 2))
```
## Demo model
Model
```{r}
source('two_way.R')
fit <- longBet_tw(y, x, 50, 10)
```

The frequentist way
```{r}
df <- data.frame(y = as.vector(y), ind = rep(1:n, t1), time = as.vector(sapply(1:t1, rep, n)))
fit.lm <- lm(y ~ factor(ind) + factor(time), data = df)
```

```{r}

```

```{r}
par(mfrow=c(1,2))
alphahat <- colMeans(fit$alphahat)
hist(alphahat-alpha, main("Hierachical alphahat - alpha"))
# plot(1:t1, rep(mu_a, mc))
```

```{r}
mc = ncol(fit$gammahat)
plot(1:t1, gamma, type = "l", col = 3, ylim = range(fit$gammahat, gamma), lwd = 2) 
for (i in 1:mc){
  lines(1:t1, fit$gammahat[,i], col = 1, lty = 2)
}
lines(1:t1, gamma, col = 3, lwd = 2)
legend("topleft", legend = c("gamma", "gammahat"), col = c(3,1), lty = c(1,2))
```
